name: "Close Issue"
author: "Kungfu Trader"
description: "Close Issue When Merged"
inputs:
  token:
    description: "secrets.GITHUB_TOKEN"
    required: true
  monday_api_key:
    description: "secrets.MONDAY_API_KEY"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
